---
- name: Add Docker’s official GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker’s apt repository
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} edge"

- name: Install Docker
  apt: name="docker-ce=18.06.3~ce~3-0~ubuntu" update_cache=true

- cron:
    name: "Remove unused docker images"
    minute: 0
    hour: "{{ docker_cleanup_cron_hours }}"
    cron_file: "docker-cleanup"
    user: root
    job: "docker system prune --all --force"
